name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake lcov
        sudo apt-get install -y libgtest-dev googletest

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage -fprofile-update=atomic -O0"

    - name: Build
      run: cmake --build build --clean-first

    - name: Run Main Application
      working-directory: ${{github.workspace}}/build
      run: ./ViterbiTrellis

    - name: Run Helper (C++)
      working-directory: ${{github.workspace}}/build
      run: ./helper

    - name: Run Helper (Python)
      run: python3 helper.py

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ./ViterbiTrellisTest

    - name: Generate Coverage Report
      run: |
        lcov --capture --directory ./build --output-file coverage.info \
             --rc geninfo_unexecuted_blocks=1 \
             --ignore-errors mismatch,negative
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info || true  # Prevent failure on warnings

    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.info
        fail_ci_if_error: false
